"""Deterministic validation helpers for the wechat-article pipeline."""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from path_utils import ensure_topic_dir, expand_user_path, latest_workflow_path

MIN_RAW_PAGE_FILES = 6
MIN_RAW_PAGE_BYTES = 20_000
MIN_EVIDENCE_CARDS = 6
MIN_SELECTED_SOURCE_FILES = 3
MAX_SELECTED_SOURCE_FILES = 8
MIN_QUOTE_CHARS = 12
MIN_EVIDENCE_DOMAINS = 3

STAGE1_RECEIPT = "research/stage1_receipt.json"
STAGE2_RECEIPT = "article/stage2_receipt.json"
STAGE3_RECEIPT = "article/stage3_receipt.json"
RECEIPT_STAGES = {
    STAGE1_RECEIPT: "stage1_observation",
    STAGE2_RECEIPT: "stage2_mechanism",
    STAGE3_RECEIPT: "stage3_insight",
}
RECEIPT_VALIDATORS = {
    STAGE1_RECEIPT: "scripts/validate_research_outputs.py",
    STAGE2_RECEIPT: "scripts/validate_mindmap_outputs.py",
    STAGE3_RECEIPT: "scripts/validate_insight_outputs.py",
}
RECEIPT_CONTRACT_VERSIONS = {
    STAGE2_RECEIPT: 2,
    STAGE3_RECEIPT: 2,
}

def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def receipt_path(topic_dir: Path, relative: str) -> Path:
    return topic_dir / relative


def clear_receipt(topic_dir: Path, relative: str) -> None:
    path = receipt_path(topic_dir, relative)
    if path.is_file():
        path.unlink()


def write_receipt(topic_dir: Path, relative: str, payload: dict[str, Any]) -> Path:
    path = receipt_path(topic_dir, relative)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = {
        **payload,
        "generated_by": RECEIPT_VALIDATORS.get(relative, "validator"),
        **(
            {"contract_version": RECEIPT_CONTRACT_VERSIONS[relative]}
            if relative in RECEIPT_CONTRACT_VERSIONS
            else {}
        ),
        "status": "passed",
        "validated_at": datetime.now(timezone.utc).isoformat(),
    }
    path.write_text(json.dumps(body, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return path


def require_receipt(topic_dir: Path, relative: str, *, next_stage: str) -> dict[str, Any]:
    path = receipt_path(topic_dir, relative)
    if not path.is_file():
        fail(
            f"Missing {relative}. {next_stage} is HARD-GATED: "
            "upstream stage validation must pass first (do not proceed on file existence alone)."
        )
    data = load_json(path)
    if not isinstance(data, dict) or data.get("status") != "passed":
        fail(f"{relative} is not a valid passed receipt. Re-run the upstream validator.")
    expected_stage = RECEIPT_STAGES.get(relative)
    if expected_stage and data.get("stage") != expected_stage:
        fail(
            f"{relative} has an invalid stage identity. Expected {expected_stage}; "
            "receipts cannot be written or simulated manually."
        )
    generated_by = data.get("generated_by")
    expected_validator = RECEIPT_VALIDATORS.get(relative)
    if generated_by is not None and generated_by != expected_validator:
        fail(
            f"{relative} was not generated by {expected_validator}. "
            "Re-run the official validator."
        )
    expected_contract = RECEIPT_CONTRACT_VERSIONS.get(relative)
    if expected_contract is not None and data.get("contract_version") != expected_contract:
        fail(
            f"{relative} uses an outdated stage contract. "
            "Re-run the upstream validator with the current skill."
        )
    return data


def load_json(path: Path) -> Any:
    if not path.is_file():
        fail(f"Missing required JSON file: {path}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        fail(f"Invalid JSON in {path}: {exc}")


def resolve_topic_dir(cli_topic_dir: str | None, probe: str) -> Path:
    if cli_topic_dir:
        return ensure_topic_dir(expand_user_path(cli_topic_dir))
    cwd = Path.cwd().resolve()
    if (cwd / probe).exists():
        return ensure_topic_dir(cwd)
    runtime_file = latest_workflow_path()
    if runtime_file.is_file():
        runtime = load_json(runtime_file)
        if isinstance(runtime, dict):
            for key in ("topic_dir", "current_topic_dir", "latest_topic_dir"):
                if runtime.get(key):
                    return ensure_topic_dir(expand_user_path(str(runtime[key])))
    fail("Cannot resolve topic directory. Run from a topic directory or pass --topic-dir.")


def nonspace_len(text: str) -> int:
    return len(re.sub(r"\s+", "", text))


def normalize_evidence_text(text: str) -> str:
    return re.sub(r"\s+", "", text)


def reject_search_snapshot(path: Path, owner: str) -> None:
    """Google pages help discover sources but never become source evidence."""
    text = path.read_text(encoding="utf-8", errors="replace")[:5000]
    compact = re.sub(r"\s+", "", text).lower()
    search_signals = (
        "google搜索结果",
        "google搜索",
        "ai概览",
        "网页搜索结果",
        "searchresults",
    )
    if sum(signal in compact for signal in search_signals) >= 2:
        fail(
            f"{owner} points to a Google/search-summary snapshot. Open and "
            "capture the original source page instead."
        )


def require_string(payload: dict[str, Any], key: str, owner: str) -> str:
    value = payload.get(key)
    if not isinstance(value, str) or not value.strip():
        fail(f"{owner}.{key} must be a non-empty string.")
    return value.strip()


def require_object(payload: dict[str, Any], key: str, owner: str) -> dict[str, Any]:
    value = payload.get(key)
    if not isinstance(value, dict):
        fail(f"{owner}.{key} must be an object.")
    return value


def require_list(payload: dict[str, Any], key: str, owner: str) -> list[Any]:
    value = payload.get(key)
    if not isinstance(value, list) or not value:
        fail(f"{owner}.{key} must be a non-empty list.")
    return value


ARTICLE_PROFILE_COMBINATIONS = {
    (
        "life_insight",
        "oral_life_insight",
        "user_oral",
        "human_scene",
    ),
    (
        "technology",
        "event_business_investment",
        "external_event",
        "tech_business_scene",
    ),
    (
        "technology",
        "practical_playbook",
        "personal_practice",
        "tech_playbook_scene",
    ),
}


def validate_article_profile(pack: dict[str, Any]) -> dict[str, Any]:
    """Validate the cross-stage content and visual route."""
    profile = require_object(pack, "article_profile", "source_pack.json")
    values = tuple(
        require_string(profile, key, "source_pack.json.article_profile").lower()
        for key in ("mode", "subtype", "source_anchor", "visual_mode")
    )
    for key in ("core_audience", "core_delivery"):
        require_string(profile, key, "source_pack.json.article_profile")
    if values not in ARTICLE_PROFILE_COMBINATIONS:
        fail(
            "source_pack.json.article_profile uses an unsupported route: "
            f"{values}. Expected one of {sorted(ARTICLE_PROFILE_COMBINATIONS)}."
        )
    mode = values[0]
    if mode == "life_insight":
        materials = pack.get("user_materials")
        if not isinstance(materials, list) or not materials:
            fail("life_insight requires non-empty source_pack.json.user_materials.")
        audience = str(profile["core_audience"])
        if "35" not in audience and "三十五" not in audience:
            fail("life_insight.core_audience must explicitly target readers aged 35+.")
    return profile


def article_route_key(profile: dict[str, Any]) -> str:
    return ":".join(
        str(profile[key]).strip().lower()
        for key in ("mode", "subtype", "source_anchor", "visual_mode")
    )


def validate_research_blueprint(topic_dir: Path) -> dict[str, Any]:
    """Validate the article route and material allocation before Stage 1 search."""
    path = topic_dir / "research" / "research_blueprint.json"
    blueprint = load_json(path)
    if not isinstance(blueprint, dict):
        fail(f"Missing or invalid Stage 1 pre-analysis blueprint: {path}")
    for key in (
        "blueprint_id",
        "topic_id",
        "article_mode",
        "article_subtype",
        "source_anchor",
        "visual_mode",
        "core_audience",
        "core_delivery",
        "type_rationale",
        "central_question",
    ):
        require_string(blueprint, key, "research_blueprint")
    route_values = tuple(
        str(blueprint[key]).strip().lower()
        for key in ("article_mode", "article_subtype", "source_anchor", "visual_mode")
    )
    if route_values not in ARTICLE_PROFILE_COMBINATIONS:
        fail(
            "research_blueprint uses an unsupported article route: "
            f"{route_values}."
        )
    if route_values[0] == "life_insight":
        audience = str(blueprint["core_audience"])
        if "35" not in audience and "三十五" not in audience:
            fail("life_insight research_blueprint must explicitly target readers aged 35+.")

    page_range = blueprint.get("planned_page_range")
    card_range = blueprint.get("planned_card_range")
    for owner, value, floor in (
        ("planned_page_range", page_range, MIN_RAW_PAGE_FILES),
        ("planned_card_range", card_range, MIN_EVIDENCE_CARDS),
    ):
        if (
            not isinstance(value, dict)
            or not isinstance(value.get("min"), int)
            or not isinstance(value.get("max"), int)
            or value["min"] < floor
            or value["max"] < value["min"]
        ):
            fail(
                f"research_blueprint.{owner} must contain integer min/max, "
                f"with min >= {floor} and max >= min."
            )
    numeric_max_share = blueprint.get("numeric_card_max_share")
    if not isinstance(numeric_max_share, (int, float)) or isinstance(numeric_max_share, bool):
        fail("research_blueprint.numeric_card_max_share must be a number.")
    if not 0 <= float(numeric_max_share) <= 1:
        fail("research_blueprint.numeric_card_max_share must be between 0 and 1.")

    plans = blueprint.get("material_plan")
    allowed_roles = {"topic_fact", "reader_context", "counter_signal", "boundary_fact"}
    if not isinstance(plans, list) or len(plans) != len(allowed_roles):
        fail("research_blueprint.material_plan must contain all four material roles.")
    plan_map: dict[str, dict[str, Any]] = {}
    total_share = 0.0
    for index, plan in enumerate(plans):
        owner = f"research_blueprint.material_plan[{index}]"
        if not isinstance(plan, dict):
            fail(f"{owner} must be an object.")
        role = require_string(plan, "material_role", owner).lower()
        if role not in allowed_roles or role in plan_map:
            fail(f"{owner}.material_role must be one unique supported role.")
        share = plan.get("target_share")
        minimum = plan.get("minimum_cards")
        maximum = plan.get("maximum_cards")
        if (
            not isinstance(share, (int, float))
            or isinstance(share, bool)
            or not 0 <= float(share) <= 1
        ):
            fail(f"{owner}.target_share must be between 0 and 1.")
        if (
            not isinstance(minimum, int)
            or isinstance(minimum, bool)
            or not isinstance(maximum, int)
            or isinstance(maximum, bool)
            or minimum < 0
            or maximum < minimum
        ):
            fail(f"{owner} minimum_cards/maximum_cards are invalid.")
        for key in ("research_questions", "preferred_sources"):
            values = plan.get(key)
            if not isinstance(values, list) or not values or any(
                not isinstance(value, str) or not value.strip() for value in values
            ):
                fail(f"{owner}.{key} must contain non-empty strings.")
        require_string(plan, "stop_condition", owner)
        total_share += float(share)
        plan_map[role] = plan
    if set(plan_map) != allowed_roles or abs(total_share - 1.0) > 0.001:
        fail("research_blueprint material roles must be complete and target_share must sum to 1.")

    if route_values[0] == "life_insight":
        if float(plan_map["topic_fact"]["target_share"]) > 0.35:
            fail("life_insight topic_fact target_share cannot exceed 0.35.")
        if float(plan_map["reader_context"]["target_share"]) < 0.35:
            fail("life_insight reader_context target_share must be at least 0.35.")
        limit_share = float(plan_map["counter_signal"]["target_share"]) + float(
            plan_map["boundary_fact"]["target_share"]
        )
        if limit_share < 0.2:
            fail(
                "life_insight counter_signal + boundary_fact target_share "
                "must be at least 0.20."
            )
        if int(plan_map["reader_context"]["minimum_cards"]) < 2:
            fail("life_insight reader_context minimum_cards must be at least 2.")
        if float(numeric_max_share) > 0.5:
            fail("life_insight numeric_card_max_share cannot exceed 0.5.")

    tracks = blueprint.get("search_tracks")
    if not isinstance(tracks, list) or len(tracks) < 4:
        fail("research_blueprint.search_tracks must contain at least 4 focused tracks.")
    covered_roles: set[str] = set()
    for index, track in enumerate(tracks):
        owner = f"research_blueprint.search_tracks[{index}]"
        if not isinstance(track, dict):
            fail(f"{owner} must be an object.")
        for key in ("id", "question", "evidence_goal", "stop_condition"):
            require_string(track, key, owner)
        role = require_string(track, "material_role", owner).lower()
        if role not in allowed_roles:
            fail(f"{owner}.material_role is unsupported.")
        queries = track.get("google_queries")
        if not isinstance(queries, list) or len(queries) < 2 or any(
            not isinstance(value, str) or not value.strip() for value in queries
        ):
            fail(f"{owner}.google_queries must contain at least 2 queries.")
        covered_roles.add(role)
    if route_values[0] == "life_insight" and not {
        "reader_context",
        "counter_signal",
        "boundary_fact",
    }.issubset(covered_roles):
        fail(
            "life_insight search_tracks must cover reader_context, counter_signal "
            "and boundary_fact before browsing."
        )

    exclusions = blueprint.get("excluded_material")
    if not isinstance(exclusions, list) or not exclusions or any(
        not isinstance(value, str) or not value.strip() for value in exclusions
    ):
        fail("research_blueprint.excluded_material must contain non-empty strings.")
    blueprint["_material_plan_map"] = plan_map
    blueprint["_article_route"] = ":".join(route_values)
    return blueprint


def markdown_shape(text: str, owner: str) -> tuple[int, int]:
    h1 = len(re.findall(r"^#\s+\S+", text, flags=re.MULTILINE))
    h2 = len(re.findall(r"^##\s+\S+", text, flags=re.MULTILINE))
    if h1 != 1:
        fail(f"{owner} must contain exactly one # title, got {h1}.")
    if h2 < 2:
        fail(f"{owner} must contain at least two ## sections, got {h2}.")
    return h1, h2


SECTION_SPLIT_RE = re.compile(r"^##\s+.+$", flags=re.MULTILINE)
NUMERIC_ID_RE = re.compile(r"^N\d{2,}$", flags=re.IGNORECASE)
COORDINATE_ID_RE = re.compile(r"^C\d{2,}$", flags=re.IGNORECASE)
SPARK_ID_RE = re.compile(r"^S\d{2,}$", flags=re.IGNORECASE)
QUANTITATIVE_SIGNAL_RE = re.compile(
    r"(?:\d+(?:[.,]\d+)?\s*(?:%|％|元|美元|港元|亿元|万亿元|万亿|亿|万|"
    r"倍|股|家|座|名|位|年|个月|月|日|小时|分钟|秒|nm|纳米|GB|TB|Mbps|"
    r"市盈率|换手率|百分点))"
    r"|(?:\b20\d{2}\b|\b\d{6}\b)"
    r"|(?:(?:零|〇|一|二|两|三|四|五|六|七|八|九|十|百|千|万|亿)+"
    r"(?:至|到|—|-)(?:零|〇|一|二|两|三|四|五|六|七|八|九|十|百|千|万|亿)+"
    r"(?:岁|年|个月|月|日|小时|分钟|秒|人|个|家|国|元|美元|倍))"
    r"|(?:(?:几|数|十几|几十|数十|上百|数百|成百上千|上千|数千|上万|数万|几十万|数十万)"
    r"(?:岁|年|个月|月|日|小时|分钟|秒|人|个|家|国|元|美元|倍))"
)


def split_major_sections(text: str) -> list[tuple[str, str]]:
    matches = list(SECTION_SPLIT_RE.finditer(text))
    if not matches:
        return []
    sections: list[tuple[str, str]] = []
    for index, match in enumerate(matches):
        title = match.group(0).lstrip("#").strip()
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        sections.append((title, text[start:end]))
    return sections


def section_length_stats(text: str) -> dict[str, Any]:
    """Informational only. Scripts never fail on voice, diction, or phrase patterns."""
    sections = split_major_sections(text)
    return {
        "section_lengths": [nonspace_len(body) for _, body in sections],
    }


def has_quantitative_signal(text: str) -> bool:
    return bool(QUANTITATIVE_SIGNAL_RE.search(text))


def _numeric_source_path(topic_dir: Path, value: str, owner: str) -> Path:
    raw_root = (topic_dir / "research" / "raw_pages").resolve()
    path = Path(value)
    if not path.is_absolute():
        path = topic_dir / path
    path = path.resolve()
    try:
        path.relative_to(raw_root)
    except ValueError:
        fail(f"{owner} must point inside {raw_root}: {path}")
    if not path.is_file():
        fail(f"{owner} does not exist: {path}")
    return path


def validate_numeric_claims(topic_dir: Path, pack: dict[str, Any]) -> dict[str, dict[str, Any]]:
    claims = pack.get("numeric_claims", [])
    if not isinstance(claims, list):
        fail("source_pack.json.numeric_claims must be a list when present.")

    result: dict[str, dict[str, Any]] = {}
    for index, claim in enumerate(claims):
        owner = f"numeric_claims[{index}]"
        if not isinstance(claim, dict):
            fail(f"{owner} must be an object.")
        for key in (
            "id",
            "claim",
            "value_text",
            "publish_text",
            "unit",
            "as_of",
            "scope",
            "risk_level",
            "calculation",
            "comparison_result",
            "allowed_wording",
            "independence_note",
        ):
            require_string(claim, key, owner)

        claim_id = str(claim["id"]).strip().upper()
        if not NUMERIC_ID_RE.fullmatch(claim_id):
            fail(f"{owner}.id must match NXX: {claim_id}")
        if claim_id in result:
            fail(f"Duplicate numeric claim id: {claim_id}")
        risk_level = str(claim["risk_level"]).strip().lower()
        if risk_level not in {"core", "supporting", "estimate"}:
            fail(f"{owner}.risk_level must be core, supporting or estimate.")
        comparison_result = str(claim["comparison_result"]).strip().lower()
        if comparison_result not in {"matched", "range", "conflict", "proprietary_estimate"}:
            fail(
                f"{owner}.comparison_result must be matched, range, conflict "
                "or proprietary_estimate."
            )
        allowed_wording = str(claim["allowed_wording"]).strip().lower()
        if allowed_wording not in {"exact", "range", "attributed", "omit"}:
            fail(f"{owner}.allowed_wording must be exact, range, attributed or omit.")
        if comparison_result == "conflict" and allowed_wording == "exact":
            fail(f"{owner} has conflicting sources and cannot allow exact wording.")
        if comparison_result == "proprietary_estimate" and allowed_wording != "attributed":
            fail(f"{owner} proprietary estimates must use attributed wording.")
        if nonspace_len(str(claim["independence_note"])) < 20:
            fail(
                f"{owner}.independence_note must explain the sources' upstream "
                "relationship and why the comparison is meaningful."
            )
        if allowed_wording == "omit":
            if str(claim["publish_text"]).strip().lower() != "omit":
                fail(f'{owner}.publish_text must be "omit" when allowed_wording is omit.')
        elif not has_quantitative_signal(str(claim["publish_text"])):
            fail(f"{owner}.publish_text must contain the verified publishable figure.")

        sources = claim.get("sources")
        if not isinstance(sources, list) or len(sources) < 2:
            fail(f"{owner}.sources must contain at least 2 comparison sources.")
        domains: set[str] = set()
        source_types: set[str] = set()
        source_quotes: set[str] = set()
        for source_index, source in enumerate(sources):
            source_owner = f"{owner}.sources[{source_index}]"
            if not isinstance(source, dict):
                fail(f"{source_owner} must be an object.")
            for key in (
                "source_url",
                "raw_page_source",
                "source_type",
                "supporting_quote",
                "role",
            ):
                require_string(source, key, source_owner)
            source_type = str(source["source_type"]).strip().lower()
            if source_type not in {"primary", "analysis", "community"}:
                fail(f"{source_owner}.source_type must be primary, analysis or community.")
            source_types.add(source_type)
            source_url = str(source["source_url"]).strip()
            parsed_url = urlparse(source_url)
            host = (parsed_url.netloc or "").lower().removeprefix("www.")
            if (
                parsed_url.scheme not in {"http", "https"}
                or not host
                or "..." in source_url
                or "…" in source_url
            ):
                fail(f"{source_owner}.source_url must include a concrete domain.")
            domains.add(host)
            path = _numeric_source_path(
                topic_dir,
                str(source["raw_page_source"]),
                f"{source_owner}.raw_page_source",
            )
            quote = normalize_evidence_text(str(source["supporting_quote"]))
            if len(quote) < MIN_QUOTE_CHARS:
                fail(f"{source_owner}.supporting_quote is too short.")
            if quote in source_quotes:
                fail(
                    f"{owner}.sources repeat the same supporting quote; "
                    "a syndicated copy is not an independent check."
                )
            source_quotes.add(quote)
            raw_text = normalize_evidence_text(
                path.read_text(encoding="utf-8", errors="replace")
            )
            if quote not in raw_text:
                fail(f"{source_owner}.supporting_quote was not found in {path}.")
        if len(domains) < 2:
            fail(f"{owner}.sources must span at least 2 independent domains.")
        if risk_level == "core" and "primary" not in source_types:
            fail(f"{owner} core figures require at least one primary source.")
        result[claim_id] = claim
    return result


def validate_numeric_refs(
    payload: dict[str, Any],
    owner: str,
    text: str,
    known_numeric_claims: dict[str, dict[str, Any]],
) -> list[str]:
    values = payload.get("numeric_claim_ids", [])
    if not isinstance(values, list):
        fail(f"{owner}.numeric_claim_ids must be a list.")
    ids = [str(value).strip().upper() for value in values if str(value).strip()]
    if has_quantitative_signal(text) and not ids:
        fail(
            f"{owner} contains a quantitative claim but has no numeric_claim_ids. "
            "Create and cross-check a numeric_claims ledger entry first."
        )
    unknown = sorted(set(ids) - set(known_numeric_claims))
    if unknown:
        fail(f"{owner}.numeric_claim_ids contains unknown IDs: {', '.join(unknown)}")
    if any(str(known_numeric_claims[value]["allowed_wording"]).lower() == "omit" for value in ids):
        fail(f"{owner} references a numeric claim whose allowed_wording is omit.")
    return ids


def validate_spark_development(
    pack: dict[str, Any],
    mechanism_ids: set[str],
    deepest_mechanism_ids: set[str],
) -> tuple[dict[str, dict[str, Any]], dict[str, Any], list[dict[str, Any]]]:
    coordinates = pack.get("coordinate_map")
    if not isinstance(coordinates, list) or not 3 <= len(coordinates) <= 6:
        fail("source_pack.json.coordinate_map must contain 3-6 mechanism-grounded coordinates.")
    coordinate_map: dict[str, dict[str, Any]] = {}
    for index, coordinate in enumerate(coordinates):
        owner = f"coordinate_map[{index}]"
        if not isinstance(coordinate, dict):
            fail(f"{owner} must be an object.")
        for key in ("id", "dimension", "mechanism_connection", "reader_connection"):
            require_string(coordinate, key, owner)
        coordinate_id = str(coordinate["id"]).strip().upper()
        if not COORDINATE_ID_RE.fullmatch(coordinate_id):
            fail(f"{owner}.id must match CXX.")
        if coordinate_id in coordinate_map:
            fail(f"Duplicate coordinate id: {coordinate_id}")
        path = coordinate.get("path")
        if (
            not isinstance(path, list)
            or not 2 <= len(path) <= 5
            or any(not isinstance(value, str) or not value.strip() for value in path)
        ):
            fail(f"{owner}.path must contain 2-5 non-empty levels.")
        basis = coordinate.get("mechanism_basis_ids")
        if not isinstance(basis, list) or not basis:
            fail(f"{owner}.mechanism_basis_ids must be a non-empty list.")
        basis_ids = [str(value).strip().upper() for value in basis if str(value).strip()]
        unknown = sorted(set(basis_ids) - mechanism_ids)
        if unknown:
            fail(f"{owner}.mechanism_basis_ids contains unknown IDs: {', '.join(unknown)}")
        coordinate_map[coordinate_id] = coordinate

    spark = pack.get("spark")
    if not isinstance(spark, dict):
        fail("source_pack.json.spark must be one object.")
    for key in (
        "id",
        "question",
        "core_tension",
        "current_judgment",
        "strongest_counterpoint",
        "reader_relation",
        "lowest_point_connection",
        "depth_boundary",
        "breadth_boundary",
        "novelty_risk",
    ):
        require_string(spark, key, "spark")
    spark_id = str(spark["id"]).strip().upper()
    if not SPARK_ID_RE.fullmatch(spark_id):
        fail("spark.id must match SXX.")

    coordinate_values = spark.get("coordinate_ids")
    if not isinstance(coordinate_values, list):
        fail("spark.coordinate_ids must be a list.")
    coordinate_ids = [
        str(value).strip().upper() for value in coordinate_values if str(value).strip()
    ]
    if not 2 <= len(coordinate_ids) <= 4 or len(set(coordinate_ids)) != len(coordinate_ids):
        fail("spark.coordinate_ids must contain 2-4 distinct coordinates.")
    unknown_coordinates = sorted(set(coordinate_ids) - set(coordinate_map))
    if unknown_coordinates:
        fail("spark.coordinate_ids contains unknown IDs: " + ", ".join(unknown_coordinates))

    mechanism_values = spark.get("mechanism_basis_ids")
    if not isinstance(mechanism_values, list) or not mechanism_values:
        fail("spark.mechanism_basis_ids must be a non-empty list.")
    spark_mechanism_ids = [
        str(value).strip().upper()
        for value in mechanism_values
        if str(value).strip()
    ]
    unknown_mechanisms = sorted(set(spark_mechanism_ids) - mechanism_ids)
    if unknown_mechanisms:
        fail(
            "spark.mechanism_basis_ids contains unknown IDs: "
            + ", ".join(unknown_mechanisms)
        )
    if not set(spark_mechanism_ids) & deepest_mechanism_ids:
        fail(
            "spark must connect to at least one of the two deepest mechanisms; "
            "it cannot be generated from the event surface."
        )

    rounds = pack.get("spark_development_rounds")
    if not isinstance(rounds, list) or not 5 <= len(rounds) <= 6:
        fail("source_pack.json.spark_development_rounds must contain 5-6 rounds.")
    focuses: list[str] = []
    previous_question_after = ""
    for index, development_round in enumerate(rounds, start=1):
        owner = f"spark_development_rounds[{index - 1}]"
        if not isinstance(development_round, dict):
            fail(f"{owner} must be an object.")
        if development_round.get("order") != index:
            fail(f"{owner}.order must equal {index}.")
        for key in (
            "focus",
            "question_before",
            "new_material_or_connection",
            "strongest_pressure",
            "revision",
            "question_after",
            "judgment_after",
            "depth_gain",
            "breadth_gain",
            "remaining_gap",
        ):
            require_string(development_round, key, owner)
        focus = str(development_round["focus"]).strip().lower()
        if focus not in {"deepen", "broaden", "challenge", "converge"}:
            fail(
                f"{owner}.focus must be deepen, broaden, challenge or converge."
            )
        focuses.append(focus)
        question_before = str(development_round["question_before"]).strip()
        question_after = str(development_round["question_after"]).strip()
        if index > 1 and question_before != previous_question_after:
            fail(
                f"{owner}.question_before must exactly match the previous "
                "round's question_after."
            )
        previous_question_after = question_after
    missing_focuses = sorted({"deepen", "broaden", "challenge", "converge"} - set(focuses))
    if missing_focuses:
        fail(
            "spark_development_rounds must include every growth focus: "
            + ", ".join(missing_focuses)
        )
    if focuses.count("deepen") < 2:
        fail("spark_development_rounds must contain at least two deepen rounds.")
    deepen_rounds = [
        development_round
        for development_round in rounds
        if str(development_round["focus"]).strip().lower() == "deepen"
    ]
    deepen_gains = {
        str(development_round["depth_gain"]).strip()
        for development_round in deepen_rounds
    }
    deepen_judgments = {
        str(development_round["judgment_after"]).strip()
        for development_round in deepen_rounds
    }
    if len(deepen_gains) != len(deepen_rounds):
        fail("Each deepen round must record a distinct depth_gain.")
    if len(deepen_judgments) != len(deepen_rounds):
        fail("Each deepen round must produce a distinct judgment_after.")
    if focuses[-1] != "converge":
        fail("The final spark development round must use focus=converge.")
    final_round = rounds[-1]
    if str(final_round["question_after"]).strip() != str(spark["question"]).strip():
        fail("The final spark round question_after must match spark.question.")
    if str(final_round["judgment_after"]).strip() != str(spark["current_judgment"]).strip():
        fail(
            "The final spark round judgment_after must match spark.current_judgment."
        )
    return coordinate_map, spark, rounds
